members/urls.py
from django.urls import path
from . import views

app_name = 'members'

urlpatterns = [
    path('', views.login_user, name='login'),
    path('logout', views.logout_user, name='logout'),
    path('register', views.register_user, name='register'),
]

mysite/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('', include('members.urls')),
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('store/', include('store.urls')),
]

polls/urls.py
from django.urls import path
from . import views

app_name = 'polls'

urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:question_id>/vote', views.vote, name='vote'),
    path('<int:question_id>/result', views.result, name='result')
]

store/urls.py
from django.urls import path
from . import views

app_name = 'store'

urlpatterns = [
    path('', views.show_store),
    path('products/', views.product_list),
    path('products/<int:product_id>/', views.product_detail),
]

members/models.py
from django.db import models

# Create your models here.

polls/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser


# Create your models here.

class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return self.question_text


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text


class User(AbstractUser):
    email = models.EmailField(unique=True)
    phone = models.CharField(max_length=11)

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []

store/models.py
from django.db import models

# Create your models here.


class Supplier(models.Model):
    name = models.CharField(max_length=250)
    email = models.EmailField()
    phone = models.CharField(max_length=11)
    address = models.CharField(max_length=300)

    def __str__(self):
        return self.name


class Product(models.Model):
    title = models.CharField(max_length=250)
    unit_price = models.DecimalField(max_digits=7, decimal_places=2)
    mfg_date = models.DateTimeField()
    exp_date = models.DateTimeField()
    supplier = models.ForeignKey(Supplier, on_delete=models.SET_NULL, null=True)

    def __str__(self):
        return self.title

members/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from polls.models import User
from django.core.exceptions import ValidationError


class CustomUserCreationForm(UserCreationForm):

    class Meta(UserCreationForm.Meta):
        model = User
        fields = UserCreationForm.Meta.fields + ('email',)

members/views.py
from django.contrib.auth import authenticate, login, logout
from django.shortcuts import render, redirect
from .forms import CustomUserCreationForm
from django.contrib import messages

# Create your views here.


def login_user(request):
    if request.method == 'POST':
        email = request.POST['email']
        password = request.POST['password']
        user = authenticate(request, email=email, password=password)
        if user is not None:
            login(request, user)
            return redirect('polls:index')
        else:
            return redirect('members:login')

    else:
        return render(request, 'members/login.html')


def logout_user(request):
    logout(request)
    return redirect('polls:index')


def register_user(request):
    if request.method == 'POST':
        form = CustomUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            email = form.cleaned_data['email']
            password = form.cleaned_data['password1']
            user = authenticate(request, username=email, password=password)
            login(request, user)
            return redirect('polls:index')
        messages.error(request, "Error in registration")
    form = CustomUserCreationForm()
    return render(request, 'members/register.html', {'form': form})

polls/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.views import generic

from .models import Question


# Create your views here.

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        return Question.objects.all()


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/details.html'


def vote(request, question_id):
    return HttpResponse("You're voting for Question %s" % question_id)


def result(request, question_id):
    return HttpResponse("You're looking at the result of Question %s" % question_id)

store/views.py
from rest_framework.decorators import api_view
from rest_framework.response import Response
from django.shortcuts import get_object_or_404
from .models import Product
from .serializers import ProductSerializer


@api_view()
def show_store(request):
    return Response('Halo from Store !')


@api_view()
def product_list(request):
    queryset = Product.objects.all()
    serializer = ProductSerializer(queryset, many=True)
    return Response(serializer.data)


@api_view(['GET', 'POST'])
def product_detail(request, product_id):
    if request.method == 'GET':
        product = get_object_or_404(Product, id=product_id)
        serializer = ProductSerializer(product)
        return Response(serializer.data)

members/templates/members/login.html
<form action="{% url 'members:login' %}" method="post">
  {% csrf_token %}
  <div class="form-group">
    <label for="Email">Email</label>
    <input type="text" class="form-control" name="email" aria-describedby="emailHelp" placeholder="Enter email">
  </div>

  <div class="form-group">
    <label for="password">Password</label>
    <input type="password" class="form-control" name="password" placeholder="Password">
  </div>

  <button type="submit" class="btn btn-primary">Sign In</button>
</form>

<a href="{% url 'members:register' %}">
  <button type="button">New User? Register!</button>
</a>

members/templates/members/register.html
{% if messages %}
{% for message in messages %}
<p style="color:red">{{ message }}</p>
{% endfor %}
{% endif %}

<h1>Register</h1>
<form action="{% url 'members:register' %}" method="post">
  {% csrf_token %}

    {{ form.as_p }}

  <button type="submit" class="btn btn-primary">Register!</button>
</form>

polls/templates/polls/details.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}
    {% for choice in question.choice_set.all %}
        <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}">
        <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br>
    {% endfor %}
</fieldset>
<input type="submit" value="Vote">
</form>

polls/templates/polls/index.html
{% if user.is_authenticated %}
    <p>Hello {{ user.get_username }}</p>
    <a href="{% url 'members:logout' %}">
        <button type="button">Log out</button>
    </a>
{% else %}
    <p>You are logged out</p>
{% endif %}

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}